kind: Namespace
apiVersion: v1
metadata:
  name: app3
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app3
  namespace: app3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: docker.io/kennethreitz/httpbin
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MESSAGE
              value: hello from app3\n
---
kind: Service
apiVersion: v1
metadata:
  name: app3
  namespace: app3
spec:
  selector:
    app: app3
  ports:
    - port: 80
      targetPort: 80
